############################################################
#
# web访问端口号  约定：80
#
############################################################
server:
  port: 80

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                         # 数据源的相关配置
    url: jdbc:mysql://47.99.55.188:3306/foodie-shop?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root

############################################################
#
# 自定义上传头像的属性
#
############################################################
system:
  face:
    url: /home/possewang/atm/picture/
    domain: http://47.99.55.188:8088/foodie-api/